import os
from dotenv import load_dotenv

from google.adk.agents import LlmAgent

# --- Load Environment Variables ---
load_dotenv()

# --- Custom Documentation Generation Tools ---

def generate_readme(state: dict) -> dict:
    """Generates a README.md file for the project.

    Args:
        state: The current session state.

    Returns:
        The updated session state.
    """
    try:
        if "generate_tests_response" in state:
            state = state["generate_tests_response"]

        project_name = state.get("project_name")
        endpoints = state.get("endpoints", [])

        if not project_name:
            raise ValueError("Missing 'project_name' in state.")

        readme_path = os.path.join(project_name, "README.md")

        with open(readme_path, "w") as f:
            f.write(f"# {project_name}\n\n")
            f.write("This project was generated by the ADK Software Development Agent.\n\n")
            f.write("## API Endpoints\n\n")
            for endpoint in endpoints:
                f.write(f"- `{endpoint}`\n")

        return state
    except Exception as e:
        raise e

